# Generated by Django 4.2.1 on 2023-05-20 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(default='emp', max_length=50),
            preserve_default=False,
        ),
    ]
